baseurl = "http://www.mariagrith.com"
title = "Maria Grith"
copyright = "&copy; 2019 Maria Grith"
languageCode = "en-us"
theme = "academic"
enableEmoji = true

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
#googleAnalytics = "UA-90427404-1"
googleAnalytics = ""

[params]
  name = "Maria Grith"
  role = "Associate Professor"
  organization = "Neoma Business School"
  avatar = "JB Delerue - 31.png"
  avatar_shape = "square"
  email = "maria.grith@neoma-bs.fr"
  address = """
Neoma Business School<br>
Finance Department<br>
Reims - Rouen - Paris<br>
<br>
Reims Campus <br>
59 Rue Pierre Taittinger<br>
BP 302 - 51061 Reims Cedex<br>
France


  """
  phone = "+33 26 77 47 47"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:grith@ese.eur.nl"

  # [[params.social]]
  #   icon = "twitter"
  #   icon_pack = "fa"
  #   link = "//twitter.com/GeorgeCushen"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=zjkn_5UAAAAJ"

  [[params.social]]
    icon = "researchgate"
    icon_pack = "ai"
    link = "https://www.researchgate.net/profile/Maria_Grith"

  # [[params.social]]
  #   icon = "github"
  #   icon_pack = "fa"
  #   link = "//github.com/mgrith"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "About Me"
  url = "#bio"
  weight = 1

[[menu.main]]
  name = "Research"
  url = "#publications"
  weight = 2

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 3

# [[menu.main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 3

# [[menu.main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 4

# [[menu.main]]
#   name = "Teaching"
#   url = "#teaching"
#   weight = 5
